# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4

before_install:
    - sudo apt-get update; true
    - source tools/travis_before_install.sh

    - which python; python --version
    - python check_bento_build.py
    - tools/build_versions.py

install:
    - python setup.py build_ext --inplace
    - python setup.py install

script: tools/travis_script.sh

after_success:
    - coveralls
