# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.ccache
addons:
  apt:
    packages:
    - ccache
    - libfreeimage3
    - texlive
    - texlive-latex-extra
    - dvipng
    - python-qt4
env:
  global:
    - GH_REF: github.com/scikit-image/docs.git
    - secure: "h25sS+tTrt1Ab8LzCFmw4nGDY7uKh4vkQ57m7KwVTua0jnI2D/mUrSiwuERF07F0w5xEoICLDUP/9P74g0JuUwSJcnyIK61lNfGXW0WLj/fMWp0iB2cOnFTTJYpUKlEmHooGVY4qqYVVAG3gaiB8s0ElPsSn5v+zoVmzq1BGark="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - source tools/travis_before_install.sh
    - which python; python --version
    - python check_bento_build.py
    - tools/build_versions.py

install:
    - python setup.py develop

script: tools/travis_script.sh

after_success:
    - coveralls
    - bash tools/deploy_docs.sh
